apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: tasker
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  selector:
    app: mongo